### ISSUE TITLE
Custom plugin not loading

### ISSUE THREAD

**Issue by mausch** [jprante/elasticsearch-plugin-deploy#5]
Even after fixing https://github.com/jprante/elasticsearch-plugin-deploy/issues/2 , my custom plugin is not loading. I think this might be because the module is being bound too late in the initialization phase and the objects that need it are already instantiated as singletons by Elasticsearch.
Concretely, my plugin registers a ScoreFunctionParser .
I was wondering what kind of interfaces have you used in the plugins you load through the deploy plugin, that might confirm my diagnosis (or reject it).

Cheers

**Comment by jprante** [comment]
I will add some documentation of how the deploy and re-deploy works. It is focused on plugins which start a service with doStart() / doStop() and uses their own modules.

A plugin which registers by "onModule()" is baked into the ES node, and this procedure can not be (easily) undone, so the module (like ScoreFunctionParser) stays in the node and can not be re-deployed.

**Comment by mausch** [comment]
I'll take a look at that, thanks!
